[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "vmp-lazy-unpack"
version = "0.1.0"
description = ""
dependencies = ["pefile", "capstone", "unicorn"]

[project.scripts]
vmp-lazy-unpack = "unpack.cli:main"

[tool.setuptools.packages.find]
include = ["unpack*"]
